import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { execFile } from 'node:child_process';
import { StdioClientTransport, type StdioServerParameters } from '@modelcontextprotocol/sdk/client/stdio.js';
import { UPSTREAM_TOOLS, type UpstreamTool } from './desktop-contract.js';
export const CUA_DRIVER_VERSION='0.7.1';
export const CUA_DRIVER_COMMAND='cua-driver';
const BASE_ENV=['PATH','HOME','USERPROFILE','TMPDIR','TEMP','TMP','LANG','LC_ALL'];
const LINUX_ENV=['DISPLAY','WAYLAND_DISPLAY','XAUTHORITY','XDG_RUNTIME_DIR','DBUS_SESSION_BUS_ADDRESS'];
const BLOCKED_ENV=/^(?:.*(?:TOKEN|KEY|SECRET|COOKIE|PASSWORD|PROXY|API).*)$|^(?:npm_config_|NODE_OPTIONS$|NODE_PATH$|PYTHONPATH$|GIT_CONFIG_|SSL_CERT_|LD_PRELOAD$|DYLD_)/i;
export function buildCuaEnvironment(env:Record<string,string|undefined>=process.env, platform=process.platform):Record<string,string> { const keys=new Set([...BASE_ENV,...(platform==='linux'?LINUX_ENV:[])]); const out:Record<string,string>={}; for(const key of keys){const value=env[key]; if(typeof value==='string'&&!BLOCKED_ENV.test(key)) out[key]=value;} return out; }
export function cuaServerParameters(env:Record<string,string|undefined>=process.env):StdioServerParameters { return { command:CUA_DRIVER_COMMAND,args:['mcp'],env:buildCuaEnvironment(env),stderr:'pipe' }; }
export interface CuaCallOptions { signal?:AbortSignal; timeout?:number; resource?:string; mutation?:boolean; }
export interface CuaTransport { callTool(name:string,args:Record<string,unknown>, options?:{signal?:AbortSignal;timeout?:number}):Promise<unknown>; listTools?():Promise<unknown>; close():Promise<void>; status?():Promise<unknown>; }
export class CuaClient implements CuaTransport {
 private client:Client|undefined; private transport:StdioClientTransport|undefined; private connecting:Promise<void>|undefined; private closed=false; private readonly queues=new Map<string,Promise<void>>();
 constructor(private readonly params:cuaServerParametersLike=cuaServerParameters(), private readonly factory?:()=>CuaTransport) {}
 async callTool(name:string,args:Record<string,unknown>,options:CuaCallOptions={}):Promise<unknown> { if(!UPSTREAM_TOOLS.includes(name as UpstreamTool)) throw new Error(`ACTION_DENIED: upstream tool ${name}`); const run=async()=>{if(options.mutation){try{return await this.rawCall(name,args,options);}catch(error){if(isDispatchLoss(error)) throw new Error('OUTCOME_UNKNOWN: mutation dispatch status unknown'); throw error;}} return this.rawCall(name,args,options);}; if(!options.resource)return run(); const previous=this.queues.get(options.resource)??Promise.resolve(); let release!:()=>void; const current=new Promise<void>(r=>{release=r}); this.queues.set(options.resource,current); await previous; try{return await run();}finally{release();if(this.queues.get(options.resource)===current)this.queues.delete(options.resource);} }
 async status():Promise<unknown>{return this.factory?this.factory().status?.():this.rawCall('health_report',{},{});}
 async close():Promise<void>{this.closed=true; const transport=this.transport; this.transport=undefined; this.client=undefined; await transport?.close(); for(const q of this.queues.values()) void q; this.queues.clear();}
 private async rawCall(name:string,args:Record<string,unknown>,options:CuaCallOptions):Promise<unknown>{ if(this.factory)return this.factory().callTool(name,args,options); const client=await this.connect(); return client.callTool({name,arguments:args},undefined,{...(options.signal?{signal:options.signal}:{}),timeout:options.timeout??15000,resetTimeoutOnProgress:true}); }
 private async connect():Promise<Client>{ if(this.closed)throw new Error('Cua client is closed.'); if(this.client)return this.client; if(this.connecting){await this.connecting;return this.client!;} this.connecting=this.open(); try{await this.connecting; return this.client!;}finally{this.connecting=undefined;} }
 private async open():Promise<void>{ await verifyCuaDriverVersion(this.params.command); const transport=new StdioClientTransport(this.params); const client=new Client({name:'pi-atlas-cua-desktop',version:'0.1.0'}); transport.stderr?.on('data',()=>undefined); await client.connect(transport); const listed=await client.listTools(); const names=new Set(listed.tools.map(tool=>tool.name)); for(const required of ['health_report','list_apps','list_windows','get_window_state']) if(!names.has(required)) throw new Error(`DRIVER_UNAVAILABLE: missing required tool ${required}`); this.transport=transport;this.client=client; }
}
type cuaServerParametersLike=StdioServerParameters;
function verifyCuaDriverVersion(command:string):Promise<void>{ return new Promise((resolve,reject)=>{ execFile(command,['--version'],{timeout:10000,env:{PATH:process.env.PATH??''}},(error,stdout)=>{ if(error){reject(new Error(`DRIVER_UNAVAILABLE: version check failed: ${error.message}`)); return;} const output=String(stdout).trim(); const expected=CUA_DRIVER_VERSION; const valid=output===expected||output===`cua-driver ${expected}`; if(!valid){reject(new Error(`DRIVER_UNAVAILABLE: expected exact Cua Driver ${expected}`)); return;} resolve(); }); }); }
function isDispatchLoss(error:unknown):boolean { return error instanceof Error && /closed|disconnect|transport|abort|timeout/i.test(error.message); }
